steps:
  - name: python:3.10
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update && apt-get install -y apt-utils python3-pip libpcre3-dev &&
        make local-install lint test

  - name: python:3.10
    entrypoint: bash
    args:
      - -c
      - |
        if [[ "${BRANCH_NAME}" == *"main"* ]];
        then
          python3 -m pip install --upgrade pip poetry setuptools keyring keyrings.google-artifactregistry-auth
          poetry config repositories.google https://${_REGION}-python.pkg.dev/${PROJECT_ID}/${_REPO}/
          poetry publish --build -r google
        fi

timeout: 600s
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REPO: celero-finance
  _REGION: us-east1