[tool.poetry]
name = "celero-bfm-fi-proto-lib"
version = "0.1.0"
description = ""
authors = ["Maicon de Menezes <maicon.menezes@celero.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
