# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: celero_bfm_fi_proto/company/company.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'celero_bfm_fi_proto/company/company.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)celero_bfm_fi_proto/company/company.proto\x12\x07\x63ompany\"c\n\x14\x43reateCompanyRequest\x12!\n\x19legal_entity_registration\x18\x01 \x01(\t\x12\x12\n\ncompany_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\"X\n\x18\x44\x65\x61\x63tivateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x13\n\x0breason_code\x18\x02 \x01(\t\x12\x13\n\x0breason_text\x18\x03 \x01(\t\"X\n\x18ReactivateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x13\n\x0breason_code\x18\x02 \x01(\t\x12\x13\n\x0breason_text\x18\x03 \x01(\t\",\n\x16\x43ompanyCommandResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t2\x8c\x02\n\x07\x43ompany\x12O\n\rCreateCompany\x12\x1d.company.CreateCompanyRequest\x1a\x1f.company.CompanyCommandResponse\x12W\n\x11\x44\x65\x61\x63tivateCompany\x12!.company.DeactivateCompanyRequest\x1a\x1f.company.CompanyCommandResponse\x12W\n\x11ReactivateCompany\x12!.company.ReactivateCompanyRequest\x1a\x1f.company.CompanyCommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'celero_bfm_fi_proto.company.company_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECOMPANYREQUEST']._serialized_start=54
  _globals['_CREATECOMPANYREQUEST']._serialized_end=153
  _globals['_DEACTIVATECOMPANYREQUEST']._serialized_start=155
  _globals['_DEACTIVATECOMPANYREQUEST']._serialized_end=243
  _globals['_REACTIVATECOMPANYREQUEST']._serialized_start=245
  _globals['_REACTIVATECOMPANYREQUEST']._serialized_end=333
  _globals['_COMPANYCOMMANDRESPONSE']._serialized_start=335
  _globals['_COMPANYCOMMANDRESPONSE']._serialized_end=379
  _globals['_COMPANY']._serialized_start=382
  _globals['_COMPANY']._serialized_end=650
# @@protoc_insertion_point(module_scope)
